### ISSUE TITLE
Error on website parsing

### ISSUE THREAD

**Issue by oleggtro** [Ampless/dsbuntis#7]
I've narrowed it down to a missing css class called `mon_title`. The error occures [here](https://github.com/Ampless/dsbuntis/blob/master/lib/src/dsbapi.dart#L262).
I don't know how this worked or still works with other schools. I can also send you the url on discord if you want...

**Comment by Erik1000** [comment]
would be pretty nice if this worked @chrissxYT

**Comment by oleggtro** [comment]
pls stop trolling

**Comment by oleggtro** [comment]
can you please give me your discord tag? I think DSBmobile doesn't actually render the html files from some src themselves but only serve precompiled stuff of the planning software. I would like to send you my version and see if that theory is true

**Comment by pixelcmtd** [comment]
I'm pretty sure that DSBMobile renders the HTML, because how would you display a high-quality/scalable otherwise? I wanted to come back to you later, because I self-assigned while in school. Feel free to send me any information that might help in solving this on Discord: chrissx#9388.
