### ISSUE TITLE
Suggestion: update readme.md to support new syntax

### ISSUE THREAD

**Issue by AstragoDE** [Ampless/dsbuntis#9]
Update the readme.md file to use the syntax of Version 7 in order to have a working documentation / example.

**Comment by pixelcmtd** [comment]
I don't think, I get what you mean. The only README breaking change I can think of is the change from `Session.parsePlans` to `parsePlans`, which I now fixed in cd9cd851d2a0fd89dcf394b74d94bb5f6b27bd92.

**Comment by AstragoDE** [comment]
That was all, thank you 😄
